name: Gatsby CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: my-gatsby-app
  SERVER_IP: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  host: ${{ secrets.SERVER_IP }}
  username: chatbotv2
  password: ${{ secrets.SERVER_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        

          
      - name: Run SSH Commands
        id: ssh
        uses: arthurvanl/action-exec-ssh@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: chatbotv2
          password: ${{ secrets.SERVER_PASSWORD }}
          ssh_!: sudo docker run -d nginx
