name: Gatsby CI/CD Pipeline

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [contentful.deploy]

env:
  IMAGE_NAME: my-gatsby-app
  SERVER_IP: ${{ secrets.SERVER_SSH_KEY }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  host: ${{ secrets.SERVER_IP }}
  username: chatbotv2
  password: ${{ secrets.SERVER_PASSWORD }}
  dockerhub_password : ${{ secrets.DOCKERHUB_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sk1297
          password: ${{ secrets.DOCKERHUB_PASSWORD }}



      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sk1297/aria-app:latest
          
          
      - name: Run SSH Commands
        id: ssh
        uses: arthurvanl/action-exec-ssh@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: chatbotv2
          password: ${{ secrets.SERVER_PASSWORD }}
          ssh_1: sudo docker pull sk1297/aria-app:latest
          ssh_2: sudo docker rm -f aria-http-server
          ssh_3: sudo docker run --name aria-http-server -d -p 83:80 sk1297/aria-app:latest
          
